application: warembo
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /index\.php
  script: home.php

- url: /
  script: index.php